name: battery
author: vu-ase
source: https://github.com/vu-ase/battery
version: 1.2.1
description: prevents the battery from under- or over-charging and reports the battery voltage

commands:
  build: make build 
  run: ./bin/battery

inputs: []
outputs:
  - voltage

configuration: []
