# Service definition
name: battery
description: Reads and reports the battery voltage

# Depends on the controller output
dependencies: []

# No outputs
outputs:
  - name: battery-voltage
    address: tcp://localhost:6000


